name: Run Tests & Notify Telegram

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # Перевіряємо код на різних версіях Python

    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Встановлення Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Кешування залежностей pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Встановлення залежностей
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Запуск pre-commit перевірок
        run: pre-commit run --all-files || (echo "❌ Pre-commit перевірки провалилися!" && exit 1)

      - name: Запуск тестів
        run: python -m unittest discover
          
      - name: Відправити повідомлення у разі провалу тестів
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=❌ Тести впали у репозиторії ${{ github.repository }}! 🚨 Перевір код: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
